import { equal, rejects } from 'node:assert/strict'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'
import test from 'node:test'
import { initializeDatabase } from '../migrations/initializeDatabase.js'
import { SqliteRetailAccessRepository } from './SqliteRetailAccessRepository.js'
import { SqliteRetailCatalogRepository } from './SqliteRetailCatalogRepository.js'
import { SqliteRetailGoodsReceiptRepository } from './SqliteRetailGoodsReceiptRepository.js'
import { SqliteRetailInventoryRepository } from './SqliteRetailInventoryRepository.js'

const context={actorType:'user' as const,actorUserId:'warehouse-user',requestId:'goods-receipt-test'}
async function fixture(run:(value:{file:string;access:SqliteRetailAccessRepository;catalog:SqliteRetailCatalogRepository;receipts:SqliteRetailGoodsReceiptRepository;inventory:SqliteRetailInventoryRepository;warehouse:{id:string};store:{id:string};product:{id:string};other:{id:string}})=>Promise<void>){const directory=mkdtempSync(join(tmpdir(),'retail-gr-'));const file=join(directory,'x.sqlite');initializeDatabase(file);const access=new SqliteRetailAccessRepository(file),catalog=new SqliteRetailCatalogRepository(file),receipts=new SqliteRetailGoodsReceiptRepository(file),inventory=new SqliteRetailInventoryRepository(file);try{const warehouse=await access.createLocation({code:'WH',name:'Warehouse',type:'central_warehouse',status:'active'},context);const store=await access.createLocation({code:'STORE',name:'Store',type:'store',status:'active'},context);const product=await catalog.createProduct({sourceId:'P1',name:'Product'},context);const other=await catalog.createProduct({sourceId:'P2',name:'Other'},context);await run({file,access,catalog,receipts,inventory,warehouse,store,product,other})}finally{inventory.close();receipts.close();catalog.close();access.close();rmSync(directory,{recursive:true,force:true})}}

test('Goods Receipt drafts have no stock effect and completion atomically records attributable Stage 4 movements',async()=>fixture(async({receipts,inventory,warehouse,store,product,other})=>{const draft=await receipts.create({receiptReference:'GR-1',locationId:warehouse.id,supplierReference:'supplier evidence',shipmentReference:'shipment evidence',lines:[{productId:product.id,quantity:3},{productId:other.id,quantity:5}]},context);equal(await inventory.findBalance(product.id,warehouse.id),undefined);await receipts.complete(draft.id,context);equal((await inventory.findBalance(product.id,warehouse.id))?.onHandQuantity,3);equal((await inventory.findBalance(other.id,warehouse.id))?.onHandQuantity,5);equal(await inventory.findBalance(product.id,store.id),undefined);const movements=await inventory.listMovements(product.id,warehouse.id);equal(movements.length,1);equal(movements[0]?.type,'goods_receipt');equal(movements[0]?.sourceType,'retail_goods_receipt');equal(movements[0]?.sourceId,draft.id);const repeated=await receipts.complete(draft.id,context);equal(repeated.status,'completed');equal((await inventory.findBalance(product.id,warehouse.id))?.onHandQuantity,3);await rejects(receipts.update(draft.id,{lines:[{productId:product.id,quantity:4}]},context),/immutable/)}))

test('Goods Receipt rejects Store destination and rolls back all evidence when any completion line becomes invalid',async()=>fixture(async({receipts,inventory,warehouse,store,product,other,catalog})=>{await rejects(receipts.create({receiptReference:'GR-STORE',locationId:store.id,lines:[{productId:product.id,quantity:1}]},context),/Central Warehouse/);const draft=await receipts.create({receiptReference:'GR-ROLLBACK',locationId:warehouse.id,lines:[{productId:product.id,quantity:2},{productId:other.id,quantity:3}]},context);await catalog.updateProduct(other.id,{name:'Other',status:'inactive'},context);await rejects(receipts.complete(draft.id,context),/inactive/);equal(await inventory.findBalance(product.id,warehouse.id),undefined);equal((await inventory.listMovements(product.id,warehouse.id)).length,0);equal((await receipts.find(draft.id))?.status,'draft')}))

test('Goods Receipt completion rolls back receipt, ledger, balance, and success evidence when its completion audit insert fails',async()=>fixture(async({file,receipts,inventory,warehouse,product})=>{const draft=await receipts.create({receiptReference:'GR-AUDIT-ROLLBACK',locationId:warehouse.id,lines:[{productId:product.id,quantity:7}]},context);const line=(await receipts.lines(draft.id))[0]!;const database=new DatabaseSync(file);try{database.exec("CREATE TRIGGER test_fail_goods_receipt_completion_audit BEFORE INSERT ON audit_events WHEN NEW.action = 'retail.goods_receipt_completed' BEGIN SELECT RAISE(ABORT, 'forced goods receipt completion audit failure'); END;");await rejects(receipts.complete(draft.id,context),/forced goods receipt completion audit failure/);const persisted=await receipts.find(draft.id);equal(persisted?.status,'draft');equal(persisted?.completedAt,undefined);equal((await receipts.lines(draft.id))[0]?.id,line.id);equal((await inventory.listMovements(product.id,warehouse.id)).filter((movement)=>movement.sourceType==='retail_goods_receipt'&&movement.sourceId===draft.id).length,0);equal(await inventory.findBalance(product.id,warehouse.id),undefined);equal((database.prepare("SELECT COUNT(*) AS count FROM retail_inventory_movements WHERE source_type = 'retail_goods_receipt' AND source_id = ?").get(draft.id) as {count:number}).count,0);equal((database.prepare("SELECT COUNT(*) AS count FROM audit_events WHERE action = 'retail.goods_receipt_completed' AND entity_id = ?").get(draft.id) as {count:number}).count,0);database.exec('DROP TRIGGER test_fail_goods_receipt_completion_audit');const completed=await receipts.complete(draft.id,context);equal(completed.status,'completed');equal((await inventory.findBalance(product.id,warehouse.id))?.onHandQuantity,7);equal((await inventory.listMovements(product.id,warehouse.id)).filter((movement)=>movement.sourceType==='retail_goods_receipt'&&movement.sourceId===draft.id).length,1);await receipts.complete(draft.id,context);equal((await inventory.findBalance(product.id,warehouse.id))?.onHandQuantity,7);equal((await inventory.listMovements(product.id,warehouse.id)).filter((movement)=>movement.sourceType==='retail_goods_receipt'&&movement.sourceId===draft.id).length,1)}finally{database.close()}}))
