import { randomUUID } from 'node:crypto'
import type { DatabaseSync } from 'node:sqlite'
import type { RetailReconciliationClassification, RetailReconciliationLine, RetailReconciliationPurpose, RetailReconciliationSession } from '@madina/retail'
import type { AuditEvent, CommandContext } from '@madina/shared'
import { appendAuditEvent } from '../audit/SqliteAuditRepository.js'
import { openDatabaseConnection } from '../connectionPolicy.js'

type SessionRow = { id: string; location_id: string; purpose: RetailReconciliationPurpose; status: 'open' | 'completed'; created_at: string; created_by: string; completed_at: string | null }
type LineRow = { session_id: string; product_id: string; expected_quantity: number; actual_quantity: number; variance: number; recorded_at: string; recorded_by: string }
const session = (r: SessionRow): RetailReconciliationSession => ({ id:r.id, locationId:r.location_id, purpose:r.purpose, status:r.status, createdAt:new Date(r.created_at), createdBy:r.created_by, completedAt:r.completed_at ? new Date(r.completed_at) : undefined })
const line = (r: LineRow): RetailReconciliationLine => ({ sessionId:r.session_id, productId:r.product_id, expectedQuantity:r.expected_quantity, actualQuantity:r.actual_quantity, variance:r.variance, classification:r.variance === 0 ? 'matched' : r.variance < 0 ? 'shortage' : 'surplus', recordedAt:new Date(r.recorded_at), recordedBy:r.recorded_by })

export class SqliteRetailReconciliationRepository {
  private readonly database: DatabaseSync
  constructor(filename:string) { this.database=openDatabaseConnection(filename) }
  async create(locationId:string,purpose:RetailReconciliationPurpose,context:CommandContext):Promise<RetailReconciliationSession> { if (purpose !== 'opening' && purpose !== 'daily') throw new Error('Retail reconciliation purpose is invalid.'); return this.tx(async()=>{ this.activeLocation(locationId); const now=new Date(); const item:RetailReconciliationSession={id:randomUUID(),locationId,purpose,status:'open',createdAt:now,createdBy:context.actorUserId ?? 'system'}; this.database.prepare('INSERT INTO retail_inventory_reconciliations (id,location_id,purpose,status,created_at,created_by,completed_at) VALUES (?,?,?,?,?,?,NULL)').run(item.id,item.locationId,item.purpose,item.status,now.toISOString(),item.createdBy); this.audit(context,item.id,'retail.reconciliation_created',{locationId,purpose}); return item }) }
  async list(locationId:string):Promise<RetailReconciliationSession[]> { return (this.database.prepare('SELECT id,location_id,purpose,status,created_at,created_by,completed_at FROM retail_inventory_reconciliations WHERE location_id=? ORDER BY created_at,id').all(locationId) as unknown as SessionRow[]).map(session) }
  async find(id:string):Promise<RetailReconciliationSession|undefined> { const r=this.database.prepare('SELECT id,location_id,purpose,status,created_at,created_by,completed_at FROM retail_inventory_reconciliations WHERE id=?').get(id) as SessionRow|undefined; return r&&session(r) }
  async lines(id:string):Promise<RetailReconciliationLine[]> { return (this.database.prepare('SELECT session_id,product_id,expected_quantity,actual_quantity,variance,recorded_at,recorded_by FROM retail_inventory_reconciliation_lines WHERE session_id=? ORDER BY product_id').all(id) as unknown as LineRow[]).map(line) }
  async recordCount(id:string,productId:string,actualQuantity:number,context:CommandContext):Promise<RetailReconciliationLine> { if (!Number.isSafeInteger(actualQuantity)||actualQuantity<0) throw new Error('Retail reconciliation actualQuantity must be a non-negative safe integer.'); return this.tx(async()=>{ const s=this.sessionOpen(id); this.activeLocation(s.locationId); this.activeProduct(productId); const expected=(this.database.prepare('SELECT on_hand_quantity FROM retail_inventory_balances WHERE product_id=? AND location_id=?').get(productId,s.locationId) as {on_hand_quantity:number}|undefined)?.on_hand_quantity ?? 0; const now=new Date(); const recordedBy=context.actorUserId ?? 'system'; this.database.prepare(`INSERT INTO retail_inventory_reconciliation_lines (session_id,product_id,expected_quantity,actual_quantity,variance,recorded_at,recorded_by) VALUES (?,?,?,?,?,?,?) ON CONFLICT(session_id,product_id) DO UPDATE SET expected_quantity=excluded.expected_quantity,actual_quantity=excluded.actual_quantity,variance=excluded.variance,recorded_at=excluded.recorded_at,recorded_by=excluded.recorded_by`).run(id,productId,expected,actualQuantity,actualQuantity-expected,now.toISOString(),recordedBy); const result={sessionId:id,productId,expectedQuantity:expected,actualQuantity,variance:actualQuantity-expected,classification:(actualQuantity===expected?'matched':actualQuantity<expected?'shortage':'surplus') as RetailReconciliationClassification,recordedAt:now,recordedBy}; this.audit(context,id,'retail.reconciliation_count_recorded',{locationId:s.locationId,productId}); return result }) }
  async complete(id:string,context:CommandContext):Promise<RetailReconciliationSession> { return this.tx(async()=>{ const s=await this.find(id); if(!s) throw new Error('Retail reconciliation not found.'); if(s.status==='completed') return s; const done={...s,status:'completed' as const,completedAt:new Date()}; this.database.prepare("UPDATE retail_inventory_reconciliations SET status='completed', completed_at=? WHERE id=? AND status='open'").run(done.completedAt.toISOString(),id); this.audit(context,id,'retail.reconciliation_completed',{locationId:s.locationId}); return done }) }
  private sessionOpen(id:string):RetailReconciliationSession { const r=this.database.prepare('SELECT id,location_id,purpose,status,created_at,created_by,completed_at FROM retail_inventory_reconciliations WHERE id=?').get(id) as SessionRow|undefined; if(!r) throw new Error('Retail reconciliation not found.'); if(r.status!=='open') throw new Error('Retail reconciliation is completed.'); return session(r) }
  private activeLocation(id:string):void { const r=this.database.prepare('SELECT status FROM retail_locations WHERE id=?').get(id) as {status:string}|undefined; if(!r) throw new Error('Retail Location not found.'); if(r.status!=='active') throw new Error('Retail Location is inactive.') }
  private activeProduct(id:string):void { const r=this.database.prepare('SELECT status FROM retail_products WHERE id=?').get(id) as {status:string}|undefined; if(!r) throw new Error('Retail Product not found.'); if(r.status!=='active') throw new Error('Retail Product is inactive.') }
  private audit(c:CommandContext,id:string,action:AuditEvent['action'],metadata:AuditEvent['metadata']):void { appendAuditEvent(this.database,{id:randomUUID(),occurredAt:new Date(),actorType:c.actorType,actorUserId:c.actorUserId,requestId:c.requestId,domain:'retail',entityType:'retail_reconciliation',entityId:id,action,metadata}) }
  private async tx<T>(f:()=>Promise<T>):Promise<T>{this.database.exec('BEGIN IMMEDIATE');try{const v=await f();this.database.exec('COMMIT');return v}catch(e){this.database.exec('ROLLBACK');throw e}}
  close():void {this.database.close()}
}
