import { createHash, generateKeyPairSync, sign } from 'node:crypto'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'
import test from 'node:test'
import { equal, rejects, throws } from 'node:assert/strict'
import { canonicalizeRetailOfflineEnvelope, RETAIL_OFFLINE_SIGNATURE_ALGORITHM, RETAIL_OFFLINE_SIGNATURE_PREFIX } from '@madina/retail'
import { initializeDatabase } from '../migrations/initializeDatabase.js'
import { SqliteAuthRepository } from '../auth/SqliteAuthRepository.js'
import { SqliteRetailAccessRepository } from './SqliteRetailAccessRepository.js'
import { SqliteRetailCatalogRepository } from './SqliteRetailCatalogRepository.js'
import { SqliteRetailInventoryRepository } from './SqliteRetailInventoryRepository.js'
import { SqliteRetailOfflineAuthorityRepository } from './SqliteRetailOfflineAuthorityRepository.js'
import { SqliteRetailOfflineSaleSyncRepository } from './SqliteRetailOfflineSaleSyncRepository.js'
import { SqliteRetailOfflineStockConflictMaterializationRepository } from './SqliteRetailOfflineStockConflictMaterializationRepository.js'
import { SqliteRetailSaleReturnRepository } from './SqliteRetailSaleReturnRepository.js'

test('verified conflict materialization is atomic, idempotent, and creates the only negative-stock seam', async () => {
  const directory=mkdtempSync(join(tmpdir(),'retail-conflict-materialization-')),file=join(directory,'x.sqlite'),context={actorType:'user' as const,actorUserId:'admin-1',requestId:'materialization'}
  initializeDatabase(file);const auth=new SqliteAuthRepository(file),access=new SqliteRetailAccessRepository(file),catalog=new SqliteRetailCatalogRepository(file),inventory=new SqliteRetailInventoryRepository(file),authority=new SqliteRetailOfflineAuthorityRepository(file),sync=new SqliteRetailOfflineSaleSyncRepository(file),materializer=new SqliteRetailOfflineStockConflictMaterializationRepository(file),returns=new SqliteRetailSaleReturnRepository(file)
  try {
    await auth.createUser({id:'admin-1',username:'Admin',normalizedUsername:'admin',email:'admin@example.test',role:'admin',status:'active',sessionVersion:1,createdAt:new Date(),updatedAt:new Date()});await auth.createUser({id:'cashier-1',username:'Cashier',normalizedUsername:'cashier',email:'cashier@example.test',role:'operator',status:'active',sessionVersion:1,createdAt:new Date(),updatedAt:new Date()})
    const location=await access.createLocation({code:'CONFLICT',name:'Conflict',type:'store',status:'active'},context);await access.configureCurrency(location.id,'USD',2,context);const product=await catalog.createProduct({sourceId:'P',name:'P'},context);await catalog.setPrice(product.id,location.id,100,context);await inventory.recordMovement({productId:product.id,locationId:location.id,quantityDelta:2,type:'opening',sourceType:'test',sourceId:'seed',sourceLineId:'seed'},context);const guard=new DatabaseSync(file);throws(()=>guard.prepare('UPDATE retail_inventory_balances SET on_hand_quantity=-1,updated_at=? WHERE product_id=? AND location_id=?').run('forged',product.id,location.id),/negative balance requires/);guard.close()
    const pair=generateKeyPairSync('ed25519'),terminal=await authority.enrollTerminal({locationId:location.id,keyAlgorithm:RETAIL_OFFLINE_SIGNATURE_ALGORITHM,publicKey:pair.publicKey.export({format:'der',type:'spki'}).toString('base64')},context),issued=await authority.issueAuthority({terminalId:terminal.id,userId:'cashier-1',locationId:location.id,expiresAt:new Date(Date.now()+60_000),permitCount:1,productIds:[product.id]},context),permit=(await authority.listPermits(issued.id))[0]!
    const envelope={schemaVersion:1 as const,offlineOperationId:'conflict-op',authorityId:issued.id,authorityVersion:issued.authorityVersion,permitId:permit.id,permitSequence:permit.sequence,terminalId:terminal.id,terminalKeyVersion:1,userId:'cashier-1',locationId:location.id,proposedSaleId:'conflict-sale',lines:[{id:'conflict-item',productId:product.id,quantity:3,unitPriceMinor:100}],currencyCode:'USD',currencyExponent:2,cashAllocation:{id:'conflict-payment',method:'cash' as const,amountMinor:300,ordinal:0 as const},subtotalMinor:300,payableTotalMinor:300,claimedOfflineCompletedAt:'2026-09-21T00:00:00.000Z'},canonical=canonicalizeRetailOfflineEnvelope(envelope),input={envelope,payloadHash:createHash('sha256').update(canonical).digest('hex'),signature:`${RETAIL_OFFLINE_SIGNATURE_PREFIX}${sign(null,Buffer.from(canonical),pair.privateKey).toString('base64')}`}
    await rejects(sync.sync(location.id,input,context),/VERIFIED_OFFLINE_STOCK_CONFLICT/);await rejects(materializer.materialize(location.id,{offlineOperationId:'missing',commandId:'missing-command'},context),/verification is required/);await catalog.updateProduct(product.id,{name:'P',status:'inactive'},context);await authority.revokeAuthority(issued.id,'after-verification',context);await authority.revokeTerminal(terminal.id,'after-verification',context)
    const failure=new DatabaseSync(file);failure.exec("CREATE TRIGGER fail_audit BEFORE INSERT ON audit_events WHEN NEW.action='retail.offline_stock_conflict_materialized' BEGIN SELECT RAISE(ABORT,'forced materialization audit failure'); END;");await rejects(materializer.materialize(location.id,{offlineOperationId:'conflict-op',commandId:'audit-failed-command'},context),/forced materialization audit failure/);equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,2);equal((failure.prepare('SELECT COUNT(*) AS count FROM retail_sales').get() as {count:number}).count,0);equal((failure.prepare('SELECT COUNT(*) AS count FROM retail_offline_stock_conflict_materialization_receipts').get() as {count:number}).count,0);failure.exec('DROP TRIGGER fail_audit');failure.exec("CREATE TRIGGER fail_incident BEFORE INSERT ON retail_offline_stock_conflict_incidents BEGIN SELECT RAISE(ABORT,'forced incident failure'); END;");await rejects(materializer.materialize(location.id,{offlineOperationId:'conflict-op',commandId:'failed-command'},context),/forced incident failure/);equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,2);failure.exec('DROP TRIGGER fail_incident');failure.close()
    const first=await materializer.materialize(location.id,{offlineOperationId:'conflict-op',commandId:'materialize-1'},context);equal(first.replayed,false);equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,-1);equal(first.incidents.length,1);equal((await catalog.findProduct(product.id))?.status,'inactive');equal((await materializer.materialize(location.id,{offlineOperationId:'conflict-op',commandId:'materialize-1'},context)).replayed,true)
    equal((await materializer.materialize(location.id,{offlineOperationId:'conflict-op',commandId:'other-command'},context)).replayed,true)
    await rejects(materializer.materialize(location.id,{offlineOperationId:'other-operation',commandId:'materialize-1'},context),/IDEMPOTENCY_CONFLICT/)
    const immutable=new DatabaseSync(file);throws(()=>immutable.prepare("UPDATE retail_offline_stock_conflict_materialization_receipts SET payload_hash='changed' WHERE command_id='materialize-1'").run(),/immutable/);throws(()=>immutable.prepare("DELETE FROM retail_offline_stock_conflict_incidents WHERE offline_operation_id='conflict-op'").run(),/immutable/);immutable.close()
    const returned=await returns.complete(location.id,{clientOperationId:'return-1',originalSaleId:'conflict-sale',items:[{saleItemId:'conflict-item',quantity:1}]},context);equal(returned.replayed,false);equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,0)
  } finally { returns.close();materializer.close();sync.close();authority.close();inventory.close();catalog.close();access.close();auth.close();rmSync(directory,{recursive:true,force:true}) }
})
