import { randomUUID } from 'node:crypto'
import type { DatabaseSync } from 'node:sqlite'
import type { RetailGoodsReceipt, RetailGoodsReceiptLine } from '@madina/retail'
import type { AuditEvent, CommandContext } from '@madina/shared'
import { appendAuditEvent } from '../audit/SqliteAuditRepository.js'
import { openDatabaseConnection } from '../connectionPolicy.js'
import { recordRetailInventoryMovement } from './SqliteRetailInventoryRepository.js'

type ReceiptRow = { id:string; receipt_reference:string; location_id:string; supplier_reference:string|null; shipment_reference:string|null; notes:string|null; status:'draft'|'completed'; created_at:string; created_by:string; completed_at:string|null }
type LineRow = { id:string; receipt_id:string; product_id:string; quantity:number }
export interface GoodsReceiptLineInput { productId:string; quantity:number }
export interface CreateGoodsReceiptInput { receiptReference:string; locationId:string; supplierReference?:string; shipmentReference?:string; notes?:string; lines:readonly GoodsReceiptLineInput[] }
export interface UpdateGoodsReceiptInput { supplierReference?:string; shipmentReference?:string; notes?:string; lines:readonly GoodsReceiptLineInput[] }
const receipt=(r:ReceiptRow):RetailGoodsReceipt=>({id:r.id,receiptReference:r.receipt_reference,locationId:r.location_id,supplierReference:r.supplier_reference??undefined,shipmentReference:r.shipment_reference??undefined,notes:r.notes??undefined,status:r.status,createdAt:new Date(r.created_at),createdBy:r.created_by,completedAt:r.completed_at?new Date(r.completed_at):undefined})
const line=(r:LineRow):RetailGoodsReceiptLine=>({id:r.id,receiptId:r.receipt_id,productId:r.product_id,quantity:r.quantity})
const text=(value:string|undefined,field:string,required=false):string|undefined=>{const result=value?.trim();if(required&&!result)throw new Error(`Retail Goods Receipt ${field} is required.`);return result||undefined}

export class SqliteRetailGoodsReceiptRepository {
  private readonly database:DatabaseSync
  constructor(filename:string){this.database=openDatabaseConnection(filename)}
  async create(input:CreateGoodsReceiptInput, context:CommandContext):Promise<RetailGoodsReceipt>{return this.tx(async()=>{this.assertCentralWarehouse(input.locationId);const lines=this.validateLines(input.lines);const item:RetailGoodsReceipt={id:randomUUID(),receiptReference:text(input.receiptReference,'receiptReference',true)!,locationId:input.locationId,supplierReference:text(input.supplierReference,'supplierReference'),shipmentReference:text(input.shipmentReference,'shipmentReference'),notes:text(input.notes,'notes'),status:'draft',createdAt:new Date(),createdBy:context.actorUserId??'system'};this.database.prepare('INSERT INTO retail_goods_receipts (id,receipt_reference,location_id,supplier_reference,shipment_reference,notes,status,created_at,created_by,completed_at) VALUES (?,?,?,?,?,?,?,?,?,NULL)').run(item.id,item.receiptReference,item.locationId,item.supplierReference??null,item.shipmentReference??null,item.notes??null,item.status,item.createdAt.toISOString(),item.createdBy);this.insertLines(item.id,lines);this.audit(context,item.id,'retail.goods_receipt_created',{locationId:item.locationId,lines:lines.length});return item})}
  async list(locationId:string):Promise<RetailGoodsReceipt[]>{return (this.database.prepare('SELECT id,receipt_reference,location_id,supplier_reference,shipment_reference,notes,status,created_at,created_by,completed_at FROM retail_goods_receipts WHERE location_id=? ORDER BY created_at,id').all(locationId) as unknown as ReceiptRow[]).map(receipt)}
  async find(id:string):Promise<RetailGoodsReceipt|undefined>{const r=this.database.prepare('SELECT id,receipt_reference,location_id,supplier_reference,shipment_reference,notes,status,created_at,created_by,completed_at FROM retail_goods_receipts WHERE id=?').get(id) as ReceiptRow|undefined;return r&&receipt(r)}
  async lines(id:string):Promise<RetailGoodsReceiptLine[]>{return (this.database.prepare('SELECT id,receipt_id,product_id,quantity FROM retail_goods_receipt_lines WHERE receipt_id=? ORDER BY id').all(id) as unknown as LineRow[]).map(line)}
  async update(id:string,input:UpdateGoodsReceiptInput,context:CommandContext):Promise<RetailGoodsReceipt>{return this.tx(async()=>{const item=this.draft(id);this.assertCentralWarehouse(item.locationId);const lines=this.validateLines(input.lines);const supplierReference=text(input.supplierReference,'supplierReference'),shipmentReference=text(input.shipmentReference,'shipmentReference'),notes=text(input.notes,'notes');this.database.prepare('UPDATE retail_goods_receipts SET supplier_reference=?,shipment_reference=?,notes=? WHERE id=?').run(supplierReference??null,shipmentReference??null,notes??null,id);this.database.prepare('DELETE FROM retail_goods_receipt_lines WHERE receipt_id=?').run(id);this.insertLines(id,lines);this.audit(context,id,'retail.goods_receipt_updated',{locationId:item.locationId,lines:lines.length});return {...item,supplierReference,shipmentReference,notes}})}
  async complete(id:string,context:CommandContext):Promise<RetailGoodsReceipt>{return this.tx(async()=>{const item=await this.find(id);if(!item)throw new Error('Retail Goods Receipt not found.');if(item.status==='completed')return item;this.assertCentralWarehouse(item.locationId);const lines=await this.lines(id);if(!lines.length)throw new Error('Retail Goods Receipt requires at least one line.');for(const itemLine of lines)this.assertActiveProduct(itemLine.productId);for(const itemLine of lines)recordRetailInventoryMovement(this.database,{productId:itemLine.productId,locationId:item.locationId,quantityDelta:itemLine.quantity,type:'goods_receipt',sourceType:'retail_goods_receipt',sourceId:item.id,sourceLineId:itemLine.id},context);const completedAt=new Date();this.database.prepare("UPDATE retail_goods_receipts SET status='completed',completed_at=? WHERE id=? AND status='draft'").run(completedAt.toISOString(),id);this.audit(context,id,'retail.goods_receipt_completed',{locationId:item.locationId,lines:lines.length});return {...item,status:'completed',completedAt}})}
  private draft(id:string):RetailGoodsReceipt{const item=this.database.prepare('SELECT id,receipt_reference,location_id,supplier_reference,shipment_reference,notes,status,created_at,created_by,completed_at FROM retail_goods_receipts WHERE id=?').get(id) as ReceiptRow|undefined;if(!item)throw new Error('Retail Goods Receipt not found.');if(item.status!=='draft')throw new Error('Completed Retail Goods Receipt is immutable.');return receipt(item)}
  private validateLines(items:readonly GoodsReceiptLineInput[]):readonly GoodsReceiptLineInput[]{if(!Array.isArray(items)||!items.length)throw new Error('Retail Goods Receipt requires at least one line.');const ids=new Set<string>();for(const item of items){if(!item||typeof item.productId!=='string'||!item.productId.trim())throw new Error('Retail Goods Receipt Product is required.');if(!Number.isSafeInteger(item.quantity)||item.quantity<=0)throw new Error('Retail Goods Receipt quantity must be a positive safe integer.');if(ids.has(item.productId))throw new Error('Retail Goods Receipt duplicate Product lines are not allowed.');ids.add(item.productId);this.assertActiveProduct(item.productId)}return items}
  private insertLines(receiptId:string,items:readonly GoodsReceiptLineInput[]):void{for(const item of items)this.database.prepare('INSERT INTO retail_goods_receipt_lines (id,receipt_id,product_id,quantity) VALUES (?,?,?,?)').run(randomUUID(),receiptId,item.productId,item.quantity)}
  private assertCentralWarehouse(locationId:string):void{const result=this.database.prepare('SELECT type,status FROM retail_locations WHERE id=?').get(locationId) as {type:string;status:string}|undefined;if(!result)throw new Error('Retail Location not found.');if(result.status!=='active')throw new Error('Retail Location is inactive.');if(result.type!=='central_warehouse')throw new Error('Retail Goods Receipt destination must be an active Central Warehouse.')}
  private assertActiveProduct(productId:string):void{const result=this.database.prepare('SELECT status FROM retail_products WHERE id=?').get(productId) as {status:string}|undefined;if(!result)throw new Error('Retail Product not found.');if(result.status!=='active')throw new Error('Retail Product is inactive.')}
  private audit(context:CommandContext,id:string,action:AuditEvent['action'],metadata:AuditEvent['metadata']):void{appendAuditEvent(this.database,{id:randomUUID(),occurredAt:new Date(),actorType:context.actorType,actorUserId:context.actorUserId,requestId:context.requestId,domain:'retail',entityType:'retail_goods_receipt',entityId:id,action,metadata})}
  private async tx<T>(operation:()=>Promise<T>):Promise<T>{this.database.exec('BEGIN IMMEDIATE');try{const value=await operation();this.database.exec('COMMIT');return value}catch(error){this.database.exec('ROLLBACK');throw error}}
  close():void{this.database.close()}
}
