import { equal, rejects } from 'node:assert/strict'
import { createHash, generateKeyPairSync, sign } from 'node:crypto'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'
import test from 'node:test'
import { RETAIL_OFFLINE_SIGNATURE_ALGORITHM, RETAIL_OFFLINE_SIGNATURE_PREFIX, canonicalizeRetailOfflineEnvelope } from '@madina/retail'
import { initializeDatabase } from '../migrations/initializeDatabase.js'
import { SqliteAuthRepository } from '../auth/SqliteAuthRepository.js'
import { SqliteRetailAccessRepository } from './SqliteRetailAccessRepository.js'
import { SqliteRetailCatalogRepository } from './SqliteRetailCatalogRepository.js'
import { SqliteRetailInventoryRepository } from './SqliteRetailInventoryRepository.js'
import { SqliteRetailOfflineAuthorityRepository } from './SqliteRetailOfflineAuthorityRepository.js'
import { SqliteRetailOfflineSaleSyncRepository } from './SqliteRetailOfflineSaleSyncRepository.js'
import { SqliteRetailSaleReturnRepository } from './SqliteRetailSaleReturnRepository.js'

test('verified offline sync is idempotent, preserves inactive historical authority products, and fails closed for stock', async () => {
  const directory=mkdtempSync(join(tmpdir(),'retail-offline-sync-')),file=join(directory,'x.sqlite')
  const context={actorType:'user' as const,actorUserId:'admin-1',requestId:'offline-sync'}
  initializeDatabase(file); const auth=new SqliteAuthRepository(file),access=new SqliteRetailAccessRepository(file),catalog=new SqliteRetailCatalogRepository(file),inventory=new SqliteRetailInventoryRepository(file),authority=new SqliteRetailOfflineAuthorityRepository(file),sync=new SqliteRetailOfflineSaleSyncRepository(file),returns=new SqliteRetailSaleReturnRepository(file)
  try {
    await auth.createUser({id:'admin-1',username:'Admin',normalizedUsername:'admin',email:'admin@example.test',role:'admin',status:'active',sessionVersion:1,createdAt:new Date(),updatedAt:new Date()});await auth.createUser({id:'cashier-1',username:'Cashier',normalizedUsername:'cashier',email:'cashier@example.test',role:'operator',status:'active',sessionVersion:1,createdAt:new Date(),updatedAt:new Date()})
    const location=await access.createLocation({code:'SYNC',name:'Sync',type:'store',status:'active'},context);await access.configureCurrency(location.id,'USD',2,context);const product=await catalog.createProduct({sourceId:'P',name:'P'},context);await catalog.setPrice(product.id,location.id,100,context);await inventory.recordMovement({productId:product.id,locationId:location.id,quantityDelta:5,type:'opening',sourceType:'test',sourceId:'seed',sourceLineId:'line'},context)
    const pair=generateKeyPairSync('ed25519'),terminal=await authority.enrollTerminal({locationId:location.id,keyAlgorithm:RETAIL_OFFLINE_SIGNATURE_ALGORITHM,publicKey:pair.publicKey.export({format:'der',type:'spki'}).toString('base64')},context),issued=await authority.issueAuthority({terminalId:terminal.id,userId:'cashier-1',locationId:location.id,expiresAt:new Date(Date.now()+60000),permitCount:3,productIds:[product.id]},context),permits=await authority.listPermits(issued.id)
    await catalog.updateProduct(product.id,{name:'P',status:'inactive'},context)
    const envelope={schemaVersion:1 as const,offlineOperationId:'op-1',authorityId:issued.id,authorityVersion:issued.authorityVersion,permitId:permits[0]!.id,permitSequence:permits[0]!.sequence,terminalId:terminal.id,terminalKeyVersion:1,userId:'cashier-1',locationId:location.id,proposedSaleId:'sale-1',lines:[{id:'item-1',productId:product.id,quantity:3,unitPriceMinor:100}],currencyCode:'USD',currencyExponent:2,cashAllocation:{id:'payment-1',method:'cash' as const,amountMinor:300,ordinal:0 as const},subtotalMinor:300,payableTotalMinor:300,claimedOfflineCompletedAt:'2026-09-20T00:00:00.000Z'}
    const canonical=canonicalizeRetailOfflineEnvelope(envelope),input={envelope,payloadHash:createHash('sha256').update(canonical).digest('hex'),signature:`${RETAIL_OFFLINE_SIGNATURE_PREFIX}${sign(null,Buffer.from(canonical),pair.privateKey).toString('base64')}`}
    await rejects(sync.sync(location.id,{...input,signature:`${input.signature.slice(0,-1)}${input.signature.endsWith('A')?'B':'A'}`},context),/signature (is invalid|verification failed)/);equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,5)
    const failureDatabase=new DatabaseSync(file);failureDatabase.exec("CREATE TRIGGER test_fail_offline_sync_audit BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT, 'forced offline sync audit failure'); END;")
    await rejects(sync.sync(location.id,input,context),/forced offline sync audit failure/);equal((failureDatabase.prepare('SELECT COUNT(*) AS count FROM retail_sales').get() as {count:number}).count,0);equal((failureDatabase.prepare('SELECT COUNT(*) AS count FROM retail_offline_sale_sync_receipts').get() as {count:number}).count,0);equal((failureDatabase.prepare('SELECT COUNT(*) AS count FROM retail_offline_sale_evidence').get() as {count:number}).count,0);failureDatabase.exec('DROP TRIGGER test_fail_offline_sync_audit');failureDatabase.close();equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,5)
    equal((await sync.sync(location.id,input,context)).replayed,false);equal((await sync.sync(location.id,input,context)).replayed,true);equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,2)
    const changed={...envelope,lines:[{...envelope.lines[0]!,quantity:4}],subtotalMinor:400,payableTotalMinor:400,cashAllocation:{...envelope.cashAllocation,amountMinor:400}},changedCanonical=canonicalizeRetailOfflineEnvelope(changed),changedInput={envelope:changed,payloadHash:createHash('sha256').update(changedCanonical).digest('hex'),signature:`${RETAIL_OFFLINE_SIGNATURE_PREFIX}${sign(null,Buffer.from(changedCanonical),pair.privateKey).toString('base64')}`};await rejects(sync.sync(location.id,changedInput,context),/IDEMPOTENCY_CONFLICT/)
    const insufficient={...envelope,offlineOperationId:'op-2',permitId:permits[1]!.id,permitSequence:permits[1]!.sequence,proposedSaleId:'sale-2',lines:[{...envelope.lines[0]!,id:'item-2',quantity:3}],subtotalMinor:300,payableTotalMinor:300,cashAllocation:{...envelope.cashAllocation,id:'payment-2'}};const insufficientCanonical=canonicalizeRetailOfflineEnvelope(insufficient),insufficientInput={envelope:insufficient,payloadHash:createHash('sha256').update(insufficientCanonical).digest('hex'),signature:`${RETAIL_OFFLINE_SIGNATURE_PREFIX}${sign(null,Buffer.from(insufficientCanonical),pair.privateKey).toString('base64')}`};await rejects(sync.sync(location.id,insufficientInput,context),/VERIFIED_OFFLINE_STOCK_CONFLICT/);equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,2)
    const verificationDatabase=new DatabaseSync(file);equal((verificationDatabase.prepare('SELECT COUNT(*) AS count FROM retail_offline_stock_conflict_verifications').get() as {count:number}).count,1);const verificationLine=verificationDatabase.prepare('SELECT quantity,authorized_unit_price_minor,observed_on_hand_quantity,initial_deficit_quantity FROM retail_offline_stock_conflict_verification_lines WHERE offline_operation_id=?').get('op-2') as {quantity:number;authorized_unit_price_minor:number;observed_on_hand_quantity:number;initial_deficit_quantity:number};equal(verificationLine.quantity,3);equal(verificationLine.authorized_unit_price_minor,100);equal(verificationLine.observed_on_hand_quantity,2);equal(verificationLine.initial_deficit_quantity,1);equal((verificationDatabase.prepare('SELECT COUNT(*) AS count FROM retail_sales WHERE id=?').get('sale-2') as {count:number}).count,0);equal((verificationDatabase.prepare('SELECT COUNT(*) AS count FROM retail_offline_sale_sync_receipts').get() as {count:number}).count,1);verificationDatabase.close()
    await rejects(sync.sync(location.id,insufficientInput,context),/VERIFIED_OFFLINE_STOCK_CONFLICT/)
    const failureConflict={...insufficient,offlineOperationId:'op-failure',permitId:permits[2]!.id,permitSequence:permits[2]!.sequence,proposedSaleId:'sale-failure',lines:[{...insufficient.lines[0]!,id:'item-failure'}],cashAllocation:{...insufficient.cashAllocation,id:'payment-failure'}},failureConflictCanonical=canonicalizeRetailOfflineEnvelope(failureConflict),failureConflictInput={envelope:failureConflict,payloadHash:createHash('sha256').update(failureConflictCanonical).digest('hex'),signature:`${RETAIL_OFFLINE_SIGNATURE_PREFIX}${sign(null,Buffer.from(failureConflictCanonical),pair.privateKey).toString('base64')}`},failureVerificationDatabase=new DatabaseSync(file);failureVerificationDatabase.exec("CREATE TRIGGER test_fail_conflict_verification_line BEFORE INSERT ON retail_offline_stock_conflict_verification_lines BEGIN SELECT RAISE(ABORT, 'forced conflict verification failure'); END;");await rejects(sync.sync(location.id,failureConflictInput,context),/forced conflict verification failure/);equal((failureVerificationDatabase.prepare('SELECT COUNT(*) AS count FROM retail_offline_stock_conflict_verifications WHERE offline_operation_id=?').get('op-failure') as {count:number}).count,0);failureVerificationDatabase.exec('DROP TRIGGER test_fail_conflict_verification_line');failureVerificationDatabase.close()
    const changedConflict={...insufficient,lines:[{...insufficient.lines[0]!,quantity:4}],subtotalMinor:400,payableTotalMinor:400,cashAllocation:{...insufficient.cashAllocation,amountMinor:400}},changedConflictCanonical=canonicalizeRetailOfflineEnvelope(changedConflict);await rejects(sync.sync(location.id,{envelope:changedConflict,payloadHash:createHash('sha256').update(changedConflictCanonical).digest('hex'),signature:`${RETAIL_OFFLINE_SIGNATURE_PREFIX}${sign(null,Buffer.from(changedConflictCanonical),pair.privateKey).toString('base64')}`},context),/IDEMPOTENCY_CONFLICT/)
    const reusedPermit={...insufficient,offlineOperationId:'op-3',proposedSaleId:'sale-3',lines:[{...insufficient.lines[0]!,id:'item-3'}],cashAllocation:{...insufficient.cashAllocation,id:'payment-3'}};const reusedPermitCanonical=canonicalizeRetailOfflineEnvelope(reusedPermit);await rejects(sync.sync(location.id,{envelope:reusedPermit,payloadHash:createHash('sha256').update(reusedPermitCanonical).digest('hex'),signature:`${RETAIL_OFFLINE_SIGNATURE_PREFIX}${sign(null,Buffer.from(reusedPermitCanonical),pair.privateKey).toString('base64')}`},context),/permit is already linked/)
    const reusedSale={...insufficient,offlineOperationId:'op-4',permitId:permits[2]!.id,permitSequence:permits[2]!.sequence,lines:[{...insufficient.lines[0]!,id:'item-4'}],cashAllocation:{...insufficient.cashAllocation,id:'payment-4'}};const reusedSaleCanonical=canonicalizeRetailOfflineEnvelope(reusedSale);await rejects(sync.sync(location.id,{envelope:reusedSale,payloadHash:createHash('sha256').update(reusedSaleCanonical).digest('hex'),signature:`${RETAIL_OFFLINE_SIGNATURE_PREFIX}${sign(null,Buffer.from(reusedSaleCanonical),pair.privateKey).toString('base64')}`},context),/identity is already linked/)
    const completed=await returns.findCompletedSale(location.id,'sale-1');equal(completed?.paymentAllocations.length,1);equal((completed?.paymentAllocations[0] as {method:string}).method,'cash');await returns.complete(location.id,{clientOperationId:'return-1',originalSaleId:'sale-1',items:[{saleItemId:'item-1',quantity:3}]},context);equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,5);await rejects(sync.sync(location.id,insufficientInput,context),/VERIFIED_OFFLINE_STOCK_CONFLICT/)
    const immutableDatabase=new DatabaseSync(file);await rejects(async()=>immutableDatabase.prepare("UPDATE retail_offline_stock_conflict_verifications SET payload_hash='changed' WHERE offline_operation_id='op-2'").run(),/immutable/);await rejects(async()=>immutableDatabase.prepare("DELETE FROM retail_offline_stock_conflict_verification_lines WHERE offline_operation_id='op-2'").run(),/immutable/);immutableDatabase.close();await authority.revokeAuthority(issued.id,'test',context);await rejects(sync.sync(location.id,insufficientInput,context),/VERIFIED_OFFLINE_STOCK_CONFLICT/)
  } finally { returns.close();sync.close();authority.close();inventory.close();catalog.close();access.close();auth.close();rmSync(directory,{recursive:true,force:true}) }
})
