import { deepEqual, equal } from 'node:assert/strict'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'
import test from 'node:test'
import { Worker } from 'node:worker_threads'
import { initializeDatabase } from '../migrations/initializeDatabase.js'
import type { SaleInput } from './SqliteRetailSaleRepository.js'
import { SqliteRetailAccessRepository } from './SqliteRetailAccessRepository.js'
import { SqliteRetailCatalogRepository } from './SqliteRetailCatalogRepository.js'
import { SqliteRetailInventoryRepository } from './SqliteRetailInventoryRepository.js'

const context={actorType:'user' as const,actorUserId:'concurrency-user',requestId:'concurrency'}
type Outcome={ok:true;replayed:boolean}|{ok:false;message:string}
function completeInWorker(filename:string,locationId:string,input:SaleInput):Promise<Outcome>{return new Promise((resolve,reject)=>{const worker=new Worker(new URL('./SqliteRetailSaleRepository.concurrentWorker.js',import.meta.url),{workerData:{filename,locationId,input,context}});worker.once('message',(message:unknown)=>{const value=message as {ok:boolean;result?:{replayed:boolean};message?:string};resolve(value.ok?{ok:true,replayed:value.result!.replayed}:{ok:false,message:value.message!})});worker.once('error',reject)})}
function counts(filename:string){const database=new DatabaseSync(filename);const count=(sql:string)=>((database.prepare(sql).get()as {count:number}).count);try{return{sales:count('SELECT COUNT(*) AS count FROM retail_sales'),items:count('SELECT COUNT(*) AS count FROM retail_sale_items'),allocations:count('SELECT COUNT(*) AS count FROM retail_payment_allocations'),movements:count("SELECT COUNT(*) AS count FROM retail_inventory_movements WHERE source_type='retail_sale'"),receipts:count("SELECT COUNT(*) AS count FROM retail_operation_receipts WHERE operation_kind='retail_sale_complete'"),audits:count("SELECT COUNT(*) AS count FROM audit_events WHERE action='retail.sale_completed'")}}finally{database.close()}}
async function fixture(run:(value:{file:string;location:{id:string};product:{id:string};inventory:SqliteRetailInventoryRepository})=>Promise<void>){const directory=mkdtempSync(join(tmpdir(),'retail-sale-concurrency-')),file=join(directory,'sales.sqlite');initializeDatabase(file);const access=new SqliteRetailAccessRepository(file),catalog=new SqliteRetailCatalogRepository(file),inventory=new SqliteRetailInventoryRepository(file);try{const location=await access.createLocation({code:'CONCURRENT',name:'Concurrent',type:'store',status:'active'},context),product=await catalog.createProduct({sourceId:'CONCURRENT',name:'Concurrent'},context);await access.configureCurrency(location.id,'USD',2,context);await catalog.setPrice(product.id,location.id,10,context);await inventory.recordMovement({productId:product.id,locationId:location.id,quantityDelta:10,type:'opening',sourceType:'test',sourceId:'concurrency',sourceLineId:'opening'},context);await run({file,location,product,inventory})}finally{inventory.close();catalog.close();access.close();rmSync(directory,{recursive:true,force:true})}}
const input=(id:string,productId:string,quantity:number,operationId=id):SaleInput=>({clientOperationId:operationId,saleId:id,lines:[{id:`${id}-line`,productId,quantity}],allocations:[{id:`${id}-payment`,method:'cash',amountMinor:quantity*10,ordinal:0}]})

test('two independent SQLite connections permit only one competing Sale beyond shared stock',async()=>fixture(async({file,location,product,inventory})=>{const results=await Promise.all([completeInWorker(file,location.id,input('compete-a',product.id,7)),completeInWorker(file,location.id,input('compete-b',product.id,7))]);equal(results.filter(result=>result.ok).length,1);const failure=results.find(result=>!result.ok);equal(failure?.ok,false);if(!failure?.ok)equal(/negative on-hand/.test(failure.message),true);equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,3);deepEqual(counts(file),{sales:1,items:1,allocations:1,movements:1,receipts:1,audits:1})}))
test('two independent SQLite connections retain both fitting Sale completions',async()=>fixture(async({file,location,product,inventory})=>{const results=await Promise.all([completeInWorker(file,location.id,input('fit-a',product.id,3)),completeInWorker(file,location.id,input('fit-b',product.id,4))]);equal(results.every(result=>result.ok),true);equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,3);deepEqual(counts(file),{sales:2,items:2,allocations:2,movements:2,receipts:2,audits:2})}))
test('two independent SQLite connections replay one exact concurrent operation',async()=>fixture(async({file,location,product,inventory})=>{const sale=input('same-sale',product.id,4,'same-operation'),results=await Promise.all([completeInWorker(file,location.id,sale),completeInWorker(file,location.id,sale)]);equal(results.every(result=>result.ok),true);equal(results.filter(result=>result.ok&&result.replayed).length,1);equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,6);deepEqual(counts(file),{sales:1,items:1,allocations:1,movements:1,receipts:1,audits:1})}))
test('two independent SQLite connections reject a concurrent mismatched operation payload',async()=>fixture(async({file,location,product,inventory})=>{const results=await Promise.all([completeInWorker(file,location.id,input('mismatch-a',product.id,3,'mismatch-operation')),completeInWorker(file,location.id,input('mismatch-b',product.id,4,'mismatch-operation'))]);equal(results.filter(result=>result.ok).length,1);const failure=results.find(result=>!result.ok);equal(failure?.ok,false);if(!failure?.ok)equal(failure.message,'IDEMPOTENCY_CONFLICT');const winner=results[0]!.ok?3:4;equal((await inventory.findBalance(product.id,location.id))?.onHandQuantity,10-winner);deepEqual(counts(file),{sales:1,items:1,allocations:1,movements:1,receipts:1,audits:1})}))
