import { deepEqual,equal,rejects } from 'node:assert/strict'
import { mkdtempSync,rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'
import { Worker } from 'node:worker_threads'
import test from 'node:test'
import { initializeDatabase } from '../migrations/initializeDatabase.js'
import { SqliteRetailAccessRepository } from './SqliteRetailAccessRepository.js'
import { SqliteRetailCatalogRepository } from './SqliteRetailCatalogRepository.js'
import { SqliteRetailInventoryRepository } from './SqliteRetailInventoryRepository.js'
import { SqliteRetailTransferRepository } from './SqliteRetailTransferRepository.js'
const c={actorType:'user' as const,actorUserId:'u',requestId:'transfer'}
async function fx(run:(x:any)=>Promise<void>){const d=mkdtempSync(join(tmpdir(),'tr-')),f=join(d,'x.sqlite');initializeDatabase(f);const a=new SqliteRetailAccessRepository(f),p=new SqliteRetailCatalogRepository(f),i=new SqliteRetailInventoryRepository(f),t=new SqliteRetailTransferRepository(f);try{const s=await a.createLocation({code:'S',name:'S',type:'store',status:'active'},c),z=await a.createLocation({code:'Z',name:'Z',type:'store',status:'active'},c),q=await p.createProduct({sourceId:'P',name:'P'},c);await i.recordMovement({productId:q.id,locationId:s.id,quantityDelta:10,type:'opening',sourceType:'test',sourceId:'seed',sourceLineId:'1'},c);await run({f,a,p,i,t,s,z,q})}finally{t.close();i.close();p.close();a.close();rmSync(d,{recursive:true,force:true})}}
test('Transfer dispatch and receive are exact, attributable and idempotent',async()=>fx(async({i,t,s,z,q}:any)=>{const x=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:4}]},c);await rejects(t.receive(x.id,c),/invalid/);await t.dispatch(x.id,c);equal((await i.findBalance(q.id,s.id))?.onHandQuantity,6);equal(await i.findBalance(q.id,z.id),undefined);await t.dispatch(x.id,c);equal((await i.listMovements(q.id,s.id)).filter((m:any)=>m.sourceType==='retail_transfer_dispatched').length,1);await t.receive(x.id,c);equal((await i.findBalance(q.id,z.id))?.onHandQuantity,4);await t.receive(x.id,c);equal((await i.listMovements(q.id,z.id)).filter((m:any)=>m.sourceType==='retail_transfer_received').length,1);await rejects(t.create({sourceLocationId:s.id,destinationLocationId:s.id,lines:[{productId:q.id,quantity:1}]},c),/distinct/)}))
test('Transfer reads use stable newest-first pagination, authorized pairs, and catalog display data',async()=>fx(async({f,a,t,s,z,q}:any)=>{const other=await a.createLocation({code:'OTHER',name:'Other',type:'store',status:'active'},c),first=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:1}]},c),second=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:2}]},c),hidden=await t.create({sourceLocationId:s.id,destinationLocationId:other.id,lines:[{productId:q.id,quantity:3}]},c),db=new DatabaseSync(f);try{db.prepare('UPDATE retail_transfers SET created_at=? WHERE id=?').run('2026-01-01T00:00:00.000Z',first.id);db.prepare('UPDATE retail_transfers SET created_at=? WHERE id=?').run('2026-01-02T00:00:00.000Z',second.id);db.prepare('UPDATE retail_transfers SET created_at=? WHERE id=?').run('2026-01-03T00:00:00.000Z',hidden.id);const page=await t.listPage(s.id,[s.id,z.id],{limit:2});equal(page.items.length,2);equal(page.items[0]?.id,second.id);equal(page.items[1]?.id,first.id);const next=await t.listPage(s.id,[s.id,z.id],{cursor:page.nextCursor,limit:2});equal(next.items.length,0);const line=(await t.lines(first.id))[0];equal(line?.productName,'P');equal(line?.productSourceId,'P');equal(line?.quantity,1)}finally{db.close()}}))
test('Transfer dispatch and receive audit failures roll back critical effects',async()=>fx(async({f,i,t,s,z,q}:any)=>{const db=new DatabaseSync(f);try{const x=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:3}]},c);db.exec("CREATE TRIGGER fail_dispatch BEFORE INSERT ON audit_events WHEN NEW.action='retail.transfer_dispatched' BEGIN SELECT RAISE(ABORT,'dispatch audit fail'); END;");await rejects(t.dispatch(x.id,c),/dispatch audit fail/);equal((await t.find(x.id))?.status,'draft');equal((await i.findBalance(q.id,s.id))?.onHandQuantity,10);equal((await i.listMovements(q.id,s.id)).filter((m:any)=>m.sourceType==='retail_transfer_dispatched').length,0);db.exec('DROP TRIGGER fail_dispatch');await t.dispatch(x.id,c);db.exec("CREATE TRIGGER fail_receive BEFORE INSERT ON audit_events WHEN NEW.action='retail.transfer_received' BEGIN SELECT RAISE(ABORT,'receive audit fail'); END;");await rejects(t.receive(x.id,c),/receive audit fail/);equal((await t.find(x.id))?.status,'dispatched');equal(await i.findBalance(q.id,z.id),undefined);equal((await i.listMovements(q.id,s.id)).filter((m:any)=>m.sourceType==='retail_transfer_dispatched').length,1);equal((await i.listMovements(q.id,z.id)).filter((m:any)=>m.sourceType==='retail_transfer_received').length,0);db.exec('DROP TRIGGER fail_receive');await t.receive(x.id,c);equal((await i.findBalance(q.id,z.id))?.onHandQuantity,3)}finally{db.close()}}))
test('Transfer draft validation rejects malformed input with no persisted effects',async()=>fx(async({f,t,s,z,q}:any)=>{const db=new DatabaseSync(f);try{const count=()=>({transfers:(db.prepare('SELECT count(*) AS n FROM retail_transfers').get()as {n:number}).n,lines:(db.prepare('SELECT count(*) AS n FROM retail_transfer_lines').get()as {n:number}).n,audits:(db.prepare("SELECT count(*) AS n FROM audit_events WHERE action='retail.transfer_created'").get()as {n:number}).n});for(const lines of [[],[null],[{productId:q.id,quantity:0}],[{productId:q.id,quantity:-1}],[{productId:q.id,quantity:1.5}],[{productId:q.id,quantity:Number.MAX_SAFE_INTEGER+1}],[{productId:q.id,quantity:1},{productId:q.id,quantity:1}],[{productId:'missing',quantity:1}]]){await rejects(t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines}as any,c));deepEqual(count(),{transfers:0,lines:0,audits:0})}await rejects(t.create({sourceLocationId:s.id,destinationLocationId:s.id,lines:[{productId:q.id,quantity:1}]},c));await rejects(t.create({sourceLocationId:'missing',destinationLocationId:z.id,lines:[{productId:q.id,quantity:1}]},c));deepEqual(count(),{transfers:0,lines:0,audits:0})}finally{db.close()}}))
test('Transfer create rejects inactive products and dispatch rolls back when a draft product becomes inactive',async()=>fx(async({p,i,t,s,z,q}:any)=>{await p.updateProduct(q.id,{name:q.name,status:'inactive'},c);await rejects(t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:1}]},c),/inactive/);await p.updateProduct(q.id,{name:q.name,status:'active'},c);const x=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:3}]},c);await p.updateProduct(q.id,{name:q.name,status:'inactive'},c);await rejects(t.dispatch(x.id,c),/inactive/);equal((await t.find(x.id))?.status,'draft');equal((await i.findBalance(q.id,s.id))?.onHandQuantity,10);equal((await i.listMovements(q.id,s.id)).length,1)}))
test('Transfer multi-line insufficient stock rolls back every earlier movement',async()=>fx(async({p,i,t,s,z,q}:any)=>{const second=await p.createProduct({sourceId:'P2',name:'P2'},c);await i.recordMovement({productId:second.id,locationId:s.id,quantityDelta:1,type:'opening',sourceType:'test',sourceId:'seed-2',sourceLineId:'2'},c);const x=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:2},{productId:second.id,quantity:2}]},c);await rejects(t.dispatch(x.id,c),/negative/);equal((await t.find(x.id))?.status,'draft');equal((await i.findBalance(q.id,s.id))?.onHandQuantity,10);equal((await i.findBalance(second.id,s.id))?.onHandQuantity,1);equal((await i.listMovements(q.id,s.id)).filter((m:any)=>m.sourceType==='retail_transfer_dispatched').length,0);equal((await i.listMovements(second.id,s.id)).filter((m:any)=>m.sourceType==='retail_transfer_dispatched').length,0)}))
const workerStartupTimeoutMs=2_000,workerResultTimeoutMs=7_000,workerCleanupTimeoutMs=2_000
type WorkerResult={ok:boolean;status?:string;error?:string}
type CleanupDiagnostic={index:number;kind:'terminate_rejected'|'terminate_timed_out'|'exit_rejected'|'exit_timed_out';error?:unknown}
type ConcurrentOptions={exitBeforeReadyIndex?:number;rejectWorkerErrors?:boolean;cleanupFailureIndex?:number;cleanupFault?:{index:number;kind:'terminate_reject'|'terminate_never'|'exit_never'};cleanupTimeoutMs?:number;onCleanupAttempt?:(index:number)=>void;onCleanupFailure?:(index:number,error:unknown)=>void;onCleanupDiagnostic?:(diagnostic:CleanupDiagnostic)=>void}
function concurrent(file:string,transferIds:readonly[string,string],operation:'dispatch'|'receive',options:ConcurrentOptions={}){
  const barrier=new SharedArrayBuffer(4),state=new Int32Array(barrier),workers=transferIds.map((transferId,index)=>new Worker(new URL('./transferConcurrencyWorker.js',import.meta.url),{workerData:{file,transferId,operation,barrier,barrierTimeoutMs:workerResultTimeoutMs,exitBeforeReady:index===options.exitBeforeReadyIndex}}))
  return new Promise<WorkerResult[]>((resolve,reject)=>{
    const results:WorkerResult[]=[],exits=new Map<Worker,Promise<number>>(),received=new Set<Worker>(),exited=new Set<Worker>()
    let settled=false,waiting=0,startupTimer:ReturnType<typeof setTimeout>|undefined,resultTimer:ReturnType<typeof setTimeout>|undefined,exitTimer:ReturnType<typeof setTimeout>|undefined
    const clearTimers=()=>{if(startupTimer)clearTimeout(startupTimer);if(resultTimer)clearTimeout(resultTimer);if(exitTimer)clearTimeout(exitTimer)}
    const stop=async()=>{clearTimers();const deadline=Date.now()+(options.cleanupTimeoutMs??workerCleanupTimeoutMs),report=(diagnostic:CleanupDiagnostic)=>{try{options.onCleanupDiagnostic?.(diagnostic)}catch{}},settle=async(operation:Promise<unknown>,index:number,stage:'terminate'|'exit')=>new Promise<boolean>(resolve=>{let settledOperation=false;const timeout=setTimeout(()=>{if(settledOperation)return;settledOperation=true;report({index,kind:`${stage}_timed_out` as CleanupDiagnostic['kind']});resolve(false)},Math.max(0,deadline-Date.now()));void operation.then(()=>{if(settledOperation)return;settledOperation=true;clearTimeout(timeout);resolve(true)},error=>{if(settledOperation)return;settledOperation=true;clearTimeout(timeout);report({index,kind:`${stage}_rejected` as CleanupDiagnostic['kind'],error});resolve(true)})}),cleanup=await Promise.allSettled(workers.map(async(worker,index)=>{options.onCleanupAttempt?.(index);const fault=options.cleanupFault?.index===index?options.cleanupFault.kind:undefined,nativeTerminate=exited.has(worker)?Promise.resolve():worker.terminate();let terminate:Promise<unknown>=nativeTerminate;if(fault==='terminate_reject')terminate=nativeTerminate.then(()=>Promise.reject(new Error('Controlled worker terminate rejection.')),()=>Promise.reject(new Error('Controlled worker terminate rejection.')));if(fault==='terminate_never'){void nativeTerminate.catch(()=>undefined);terminate=new Promise<never>(()=>{})}if(!await settle(terminate,index,'terminate'))return;const exit=fault==='exit_never'?new Promise<never>(()=>{}):exits.get(worker)!;await settle(exit,index,'exit');if(index===options.cleanupFailureIndex)throw new Error('Controlled worker cleanup failure.')}));cleanup.forEach((result,index)=>{if(result.status==='rejected')options.onCleanupFailure?.(index,result.reason)})}
    const fail=(error:Error)=>{if(settled)return;settled=true;void stop().then(()=>reject(error),()=>reject(error))}
    const succeed=()=>{if(settled)return;if(resultTimer)clearTimeout(resultTimer);exitTimer=setTimeout(()=>fail(new Error('Transfer concurrency workers did not exit in time.')),workerResultTimeoutMs);void Promise.all([...exits.values()]).then(codes=>{if(codes.some(code=>code!==0))return fail(new Error('Transfer concurrency worker exited unsuccessfully.'));if(settled)return;settled=true;clearTimers();resolve(results)},fail)}
    startupTimer=setTimeout(()=>fail(new Error('Transfer concurrency workers did not become ready in time.')),workerStartupTimeoutMs)
    for(const worker of workers){
      exits.set(worker,new Promise<number>(resolveExit=>worker.once('exit',resolveExit)))
      worker.once('error',error=>fail(error))
      worker.on('exit',code=>{exited.add(worker);if(!received.has(worker)&&!settled)fail(new Error(`Transfer concurrency worker exited before result (${code}).`))})
      worker.on('message',(message:{ready?:boolean;ok?:boolean;status?:string;error?:string})=>{
        if(settled)return
        if(message.ready){if(++waiting===workers.length){if(startupTimer)clearTimeout(startupTimer);Atomics.store(state,0,1);Atomics.notify(state,0,workers.length);resultTimer=setTimeout(()=>fail(new Error('Transfer concurrency workers did not return results in time.')),workerResultTimeoutMs)};return}
        if(received.has(worker))return;received.add(worker);if(options.rejectWorkerErrors&&message.ok!==true){fail(new Error(message.error??'Transfer concurrency worker operation failed.'));return}results.push({ok:message.ok===true,status:message.status,error:message.error})
        if(results.length===workers.length)succeed()
      })
    }
  })
}
function transferAuditCount(file:string,transferId:string,action:'retail.transfer_dispatched'|'retail.transfer_received'){const db=new DatabaseSync(file);try{return(db.prepare('SELECT count(*) AS n FROM audit_events WHERE entity_id=? AND action=?').get(transferId,action)as {n:number}).n}finally{db.close()}}
test('Transfer concurrent workers preserve exactly-once dispatch and receive effects',async()=>fx(async({f,i,t,s,z,q}:any)=>{const x=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:4}]},c),dispatch=await concurrent(f,[x.id,x.id],'dispatch');equal(dispatch.length,2);equal((await t.find(x.id))?.status,'dispatched');equal((await i.findBalance(q.id,s.id))?.onHandQuantity,6);equal((await i.listMovements(q.id,s.id)).filter((m:any)=>m.sourceType==='retail_transfer_dispatched').length,1);equal(transferAuditCount(f,x.id,'retail.transfer_dispatched'),1);const receive=await concurrent(f,[x.id,x.id],'receive');equal(receive.length,2);equal((await t.find(x.id))?.status,'received');equal((await i.findBalance(q.id,z.id))?.onHandQuantity,4);equal((await i.listMovements(q.id,z.id)).filter((m:any)=>m.sourceType==='retail_transfer_received').length,1);equal(transferAuditCount(f,x.id,'retail.transfer_received'),1)}))
test('Competing worker dispatches leave one draft and never oversell source stock',async()=>fx(async({f,i,t,s,z,q}:any)=>{const first=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:7}]},c),second=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:7}]},c),results=await concurrent(f,[first.id,second.id],'dispatch'),states=[(await t.find(first.id))?.status,(await t.find(second.id))?.status],winner=states[0]==='dispatched'?first:second,loser=winner.id===first.id?second:first;equal(results.filter(result=>result.ok).length,1);equal(results.filter(result=>result.error==='RetailInsufficientStockError').length,1);equal(states.filter(state=>state==='dispatched').length,1);equal(states.filter(state=>state==='draft').length,1);equal((await i.findBalance(q.id,s.id))?.onHandQuantity,3);equal((await i.listMovements(q.id,s.id)).filter((m:any)=>m.sourceType==='retail_transfer_dispatched').length,1);equal(transferAuditCount(f,winner.id,'retail.transfer_dispatched'),1);equal(transferAuditCount(f,loser.id,'retail.transfer_dispatched'),0)}))
test('Transfer concurrency helper rejects an early worker exit and releases the temporary database',async()=>fx(async({f,i,t,s,z,q}:any)=>{const x=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:4}]},c);await rejects(concurrent(f,[x.id,x.id],'dispatch',{exitBeforeReadyIndex:0}),/exited before result/);equal((await t.find(x.id))?.status,'draft');equal((await i.findBalance(q.id,s.id))?.onHandQuantity,10);equal(transferAuditCount(f,x.id,'retail.transfer_dispatched'),0);await t.dispatch(x.id,c);equal((await t.find(x.id))?.status,'dispatched')}))
test('Transfer concurrency helper preserves an operation error when cleanup reports a failure',async()=>fx(async({f,i,t,s,z,q}:any)=>{const x=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:11}]},c),cleanupAttempts:number[]=[],cleanupFailures:Array<{index:number;error:unknown}>=[];await rejects(concurrent(f,[x.id,x.id],'dispatch',{rejectWorkerErrors:true,cleanupFailureIndex:1,onCleanupAttempt:index=>cleanupAttempts.push(index),onCleanupFailure:(index,error)=>cleanupFailures.push({index,error})}),/RetailInsufficientStockError/);deepEqual(cleanupAttempts.sort(),[0,1]);equal(cleanupFailures.length,1);equal(cleanupFailures[0]?.index,1);equal((cleanupFailures[0]?.error as Error).message,'Controlled worker cleanup failure.');equal((await t.find(x.id))?.status,'draft');equal((await i.findBalance(q.id,s.id))?.onHandQuantity,10);equal(transferAuditCount(f,x.id,'retail.transfer_dispatched'),0);await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:1}]},c)}))
async function verifyBoundedCleanupFault(kind:'terminate_reject'|'terminate_never'|'exit_never',expected:CleanupDiagnostic['kind']){await fx(async({f,i,t,s,z,q}:any)=>{const x=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:11}]},c),cleanupAttempts:number[]=[],diagnostics:CleanupDiagnostic[]=[],started=Date.now();await rejects(concurrent(f,[x.id,x.id],'dispatch',{rejectWorkerErrors:true,cleanupFault:{index:1,kind},cleanupTimeoutMs:100,onCleanupAttempt:index=>cleanupAttempts.push(index),onCleanupDiagnostic:diagnostic=>diagnostics.push(diagnostic)}),/RetailInsufficientStockError/);equal(Date.now()-started<1_000,true);deepEqual(cleanupAttempts.sort(),[0,1]);equal(diagnostics.some(diagnostic=>diagnostic.index===1&&diagnostic.kind===expected),true);equal((await t.find(x.id))?.status,'draft');equal((await i.findBalance(q.id,s.id))?.onHandQuantity,10);equal(transferAuditCount(f,x.id,'retail.transfer_dispatched'),0)})}
test('Transfer concurrency helper preserves the operation error when terminate rejects',async()=>verifyBoundedCleanupFault('terminate_reject','terminate_rejected'))
test('Transfer concurrency helper bounds a never-settling terminate promise',async()=>verifyBoundedCleanupFault('terminate_never','terminate_timed_out'))
test('Transfer concurrency helper bounds a never-settling exit promise',async()=>verifyBoundedCleanupFault('exit_never','exit_timed_out'))
