import { equal,rejects } from 'node:assert/strict'
import { mkdtempSync,rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'
import test from 'node:test'
import { initializeDatabase } from '../migrations/initializeDatabase.js'
import { SqliteRetailAccessRepository } from './SqliteRetailAccessRepository.js'
import { SqliteRetailCatalogRepository } from './SqliteRetailCatalogRepository.js'
import { SqliteRetailInventoryRepository } from './SqliteRetailInventoryRepository.js'
import { SqliteRetailTransferRepository } from './SqliteRetailTransferRepository.js'
const c={actorType:'user' as const,actorUserId:'u',requestId:'transfer'}
async function fx(run:(x:any)=>Promise<void>){const d=mkdtempSync(join(tmpdir(),'tr-')),f=join(d,'x.sqlite');initializeDatabase(f);const a=new SqliteRetailAccessRepository(f),p=new SqliteRetailCatalogRepository(f),i=new SqliteRetailInventoryRepository(f),t=new SqliteRetailTransferRepository(f);try{const s=await a.createLocation({code:'S',name:'S',type:'store',status:'active'},c),z=await a.createLocation({code:'Z',name:'Z',type:'store',status:'active'},c),q=await p.createProduct({sourceId:'P',name:'P'},c);await i.recordMovement({productId:q.id,locationId:s.id,quantityDelta:10,type:'opening',sourceType:'test',sourceId:'seed',sourceLineId:'1'},c);await run({f,a,p,i,t,s,z,q})}finally{t.close();i.close();p.close();a.close();rmSync(d,{recursive:true,force:true})}}
test('Transfer dispatch and receive are exact, attributable and idempotent',async()=>fx(async({i,t,s,z,q}:any)=>{const x=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:4}]},c);await rejects(t.receive(x.id,c),/invalid/);await t.dispatch(x.id,c);equal((await i.findBalance(q.id,s.id))?.onHandQuantity,6);equal(await i.findBalance(q.id,z.id),undefined);await t.dispatch(x.id,c);equal((await i.listMovements(q.id,s.id)).filter((m:any)=>m.sourceType==='retail_transfer_dispatched').length,1);await t.receive(x.id,c);equal((await i.findBalance(q.id,z.id))?.onHandQuantity,4);await t.receive(x.id,c);equal((await i.listMovements(q.id,z.id)).filter((m:any)=>m.sourceType==='retail_transfer_received').length,1);await rejects(t.create({sourceLocationId:s.id,destinationLocationId:s.id,lines:[{productId:q.id,quantity:1}]},c),/distinct/)}))
test('Transfer dispatch and receive audit failures roll back critical effects',async()=>fx(async({f,i,t,s,z,q}:any)=>{const db=new DatabaseSync(f);try{const x=await t.create({sourceLocationId:s.id,destinationLocationId:z.id,lines:[{productId:q.id,quantity:3}]},c);db.exec("CREATE TRIGGER fail_dispatch BEFORE INSERT ON audit_events WHEN NEW.action='retail.transfer_dispatched' BEGIN SELECT RAISE(ABORT,'dispatch audit fail'); END;");await rejects(t.dispatch(x.id,c),/dispatch audit fail/);equal((await t.find(x.id))?.status,'draft');equal((await i.findBalance(q.id,s.id))?.onHandQuantity,10);equal((await i.listMovements(q.id,s.id)).filter((m:any)=>m.sourceType==='retail_transfer_dispatched').length,0);db.exec('DROP TRIGGER fail_dispatch');await t.dispatch(x.id,c);db.exec("CREATE TRIGGER fail_receive BEFORE INSERT ON audit_events WHEN NEW.action='retail.transfer_received' BEGIN SELECT RAISE(ABORT,'receive audit fail'); END;");await rejects(t.receive(x.id,c),/receive audit fail/);equal((await t.find(x.id))?.status,'dispatched');equal(await i.findBalance(q.id,z.id),undefined);equal((await i.listMovements(q.id,s.id)).filter((m:any)=>m.sourceType==='retail_transfer_dispatched').length,1);equal((await i.listMovements(q.id,z.id)).filter((m:any)=>m.sourceType==='retail_transfer_received').length,0);db.exec('DROP TRIGGER fail_receive');await t.receive(x.id,c);equal((await i.findBalance(q.id,z.id))?.onHandQuantity,3)}finally{db.close()}}))
