import { cleanup, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { RetailProducts } from './RetailProducts'

const api = vi.hoisted(() => ({ getRetailLocations: vi.fn(), getRetailProducts: vi.fn(), getRetailProductPrice: vi.fn(), getRetailProductDetail: vi.fn(), createRetailProduct: vi.fn(), addRetailProductBarcode: vi.fn(), setRetailProductPrice: vi.fn(), updateRetailProductAtLocation: vi.fn(), downloadRetailProductTemplate: vi.fn(), preflightRetailProductWorkbook: vi.fn(), importRetailProductsWithPrices: vi.fn() }))
const auth = vi.hoisted(() => ({ useAuth: vi.fn() }))
vi.mock('../../shared/api/retailApi', () => api)
vi.mock('../../context/useAuth', () => auth)
const location = { id: 'store-1', code: 'STORE', name: 'Store', type: 'store', status: 'active', currencyCode: 'UZS', currencyExponent: 0 }
const product = { id: 'uuid-product', sourceId: 'SKU-1', name: 'Чай', status: 'active', baseUnit: 'piece', createdAt: new Date(), updatedAt: new Date() }
const admin = { id: 'admin-1', username: 'admin', role: 'admin' as const }
beforeEach(() => { const result = { dryRun: false, canApply: true, outcomes: [{ sourceRef: '4', kind: 'created', price: { kind: 'created', unitPriceMinor: 15000 } }], summary: { created: 1, updated: 0, no_op: 0, conflict: 0, quarantine: 0 } }; auth.useAuth.mockReturnValue({ user: admin }); api.getRetailLocations.mockResolvedValue([location]); api.getRetailProducts.mockResolvedValue([product]); api.getRetailProductPrice.mockResolvedValue(12500); api.getRetailProductDetail.mockResolvedValue({ product, barcodes: [{ value: '460000000001' }] }); api.createRetailProduct.mockResolvedValue({ ...product, id: 'created' }); api.addRetailProductBarcode.mockResolvedValue(undefined); api.setRetailProductPrice.mockResolvedValue(undefined); api.updateRetailProductAtLocation.mockResolvedValue(product); api.importRetailProductsWithPrices.mockResolvedValue(result); api.preflightRetailProductWorkbook.mockResolvedValue({ rows: [{ sourceRef: '4', sourceId: 'SKU-2', name: 'Кофе', status: 'active', unitPriceMinor: 15000 }], result: { ...result, dryRun: true } }) })
afterEach(() => { cleanup(); vi.clearAllMocks() })
async function submitManualProduct() { const user = userEvent.setup(); await user.click(screen.getByRole('button', { name: 'Добавить товар' })); await user.type(screen.getByLabelText('Артикул'), 'SKU-2'); await user.type(screen.getByLabelText('Наименование'), 'Кофе'); await user.type(screen.getByLabelText('Штрихкод'), '460000000002'); await user.type(screen.getByLabelText('Цена продажи'), '15000'); await user.click(screen.getByRole('button', { name: 'Сохранить' })); return user }

it('renders a Retail catalog using article instead of UUID and its location price', async () => { render(<RetailProducts />); await screen.findByText('Чай'); expect(screen.getByText('SKU-1')).toBeTruthy(); expect(screen.queryByText('uuid-product')).toBeNull(); expect(screen.getByText(/12\s*500/)).toBeTruthy() })
it('uses Retail primitives for manual creation and price without inventory actions', async () => { render(<RetailProducts />); await screen.findByText('Чай'); await submitManualProduct(); await waitFor(() => expect(api.createRetailProduct).toHaveBeenCalledWith({ sourceId: 'SKU-2', name: 'Кофе', status: 'active' })); expect(api.setRetailProductPrice).toHaveBeenCalledWith('store-1', 'created', 15000); expect(api.importRetailProductsWithPrices).not.toHaveBeenCalled() })
it('keeps a product-create failure separate from partial completion', async () => { api.createRetailProduct.mockRejectedValueOnce(new Error('create rejected')); render(<RetailProducts />); await screen.findByText('Чай'); await submitManualProduct(); await screen.findByText('create rejected'); expect(api.addRetailProductBarcode).not.toHaveBeenCalled(); expect(api.setRetailProductPrice).not.toHaveBeenCalled() })
it('identifies a barcode partial failure, refreshes the catalog, and does not retry product creation', async () => { api.addRetailProductBarcode.mockRejectedValueOnce(new Error('barcode rejected')); render(<RetailProducts />); await screen.findByText('Чай'); await submitManualProduct(); await screen.findByText(/штрихкод не сохранён/); expect(api.createRetailProduct).toHaveBeenCalledTimes(1); await waitFor(() => expect(api.getRetailProducts).toHaveBeenCalledTimes(2)); expect(api.setRetailProductPrice).not.toHaveBeenCalled() })
it('identifies a sale-price partial failure after barcode persistence and does not retry product creation', async () => { api.setRetailProductPrice.mockRejectedValueOnce(new Error('price rejected')); render(<RetailProducts />); await screen.findByText('Чай'); await submitManualProduct(); await screen.findByText(/цена продажи не сохранена/); expect(api.addRetailProductBarcode).toHaveBeenCalledWith('created', '460000000002'); expect(api.createRetailProduct).toHaveBeenCalledTimes(1); await waitFor(() => expect(api.getRetailProducts).toHaveBeenCalledTimes(2)) })
it('requires a successful preview before the atomic import apply', async () => { render(<RetailProducts />); const user = userEvent.setup(); await screen.findByText('Чай'); const file = new File(['xlsx'], 'catalog.xlsx', { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }); await user.upload(screen.getByLabelText('Загрузить товары'), file); await screen.findByText('Предварительная проверка импорта'); expect(api.importRetailProductsWithPrices).not.toHaveBeenCalled(); await user.click(screen.getByRole('button', { name: 'Подтвердить импорт' })); await waitFor(() => expect(api.importRetailProductsWithPrices).toHaveBeenCalledWith('store-1', false, expect.any(Array))) })
it('hides mutation and import controls for a read-only user', async () => { auth.useAuth.mockReturnValue({ user: { id: 'viewer', username: 'viewer', role: 'viewer' } }); render(<RetailProducts />); await screen.findByText('Чай'); expect(screen.queryByRole('button', { name: 'Добавить товар' })).toBeNull(); expect(screen.queryByLabelText('Загрузить товары')).toBeNull() })
it('submits a manual edit as one atomic Retail request', async () => { render(<RetailProducts />); const user = userEvent.setup(); await screen.findByText('Чай'); await user.click(screen.getByRole('button', { name: 'Изменить' })); await user.clear(screen.getByLabelText('Наименование')); await user.type(screen.getByLabelText('Наименование'), 'Обновлённый чай'); await user.type(screen.getByLabelText('Добавить штрихкод'), '460000000002'); await user.clear(screen.getByLabelText('Цена продажи')); await user.type(screen.getByLabelText('Цена продажи'), '15000'); await user.selectOptions(screen.getByLabelText('Статус'), 'inactive'); await user.click(screen.getByRole('button', { name: 'Сохранить' })); await waitFor(() => expect(api.updateRetailProductAtLocation).toHaveBeenCalledWith('store-1', 'uuid-product', { name: 'Обновлённый чай', status: 'inactive', appendBarcode: '460000000002', unitPriceMinor: 15000 })); expect(api.addRetailProductBarcode).not.toHaveBeenCalled(); expect(api.setRetailProductPrice).not.toHaveBeenCalled() })
