import { RETAIL_OFFLINE_SIGNATURE_ALGORITHM, exportRetailOfflineTerminalPublicKey, signRetailOfflineEnvelope, type RetailOfflineEnvelope, type RetailOfflineSignedEnvelope } from '@madina/retail'

const databaseName = 'madina-crm:retail-offline-terminal-identity:v1', storeName = 'identity', recordKey = 'current'
type StoredIdentity = { version: 1; publicKeyAlgorithm: typeof RETAIL_OFFLINE_SIGNATURE_ALGORITHM; publicKey: string; privateKey: CryptoKey; terminalId?: string; locationId?: string; currentKeyVersion?: number }
export type TerminalIdentityState = 'KEY_GENERATED' | 'ENROLLED'
export interface TerminalIdentity { readonly version: 1; readonly state: TerminalIdentityState; readonly publicKeyAlgorithm: typeof RETAIL_OFFLINE_SIGNATURE_ALGORITHM; readonly publicKey: string; readonly terminalId?: string; readonly locationId?: string; readonly currentKeyVersion?: number; signOfflineEnvelope(envelope: RetailOfflineEnvelope): Promise<RetailOfflineSignedEnvelope> }
export class TerminalIdentityError extends Error {}
function database(): Promise<IDBDatabase> { return new Promise((resolve,reject)=>{const request=indexedDB.open(databaseName,1);request.onupgradeneeded=()=>request.result.createObjectStore(storeName);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new TerminalIdentityError('Retail Offline Terminal identity storage is unavailable.',{cause:request.error}))}) }
function read(db:IDBDatabase):Promise<StoredIdentity|undefined>{return new Promise((resolve,reject)=>{const request=db.transaction(storeName,'readonly').objectStore(storeName).get(recordKey);request.onsuccess=()=>resolve(request.result as StoredIdentity|undefined);request.onerror=()=>reject(new TerminalIdentityError('Retail Offline Terminal identity cannot be read.',{cause:request.error}))})}
function write(db:IDBDatabase,value:StoredIdentity):Promise<void>{return new Promise((resolve,reject)=>{const transaction=db.transaction(storeName,'readwrite');transaction.objectStore(storeName).put(value,recordKey);transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(new TerminalIdentityError('Retail Offline Terminal identity cannot be saved.',{cause:transaction.error}))})}
async function identity(value:StoredIdentity):Promise<TerminalIdentity>{const enrolled=[value.terminalId,value.locationId,value.currentKeyVersion],validEnrollment=enrolled.every(item=>item===undefined)||(typeof value.terminalId==='string'&&Boolean(value.terminalId.trim())&&typeof value.locationId==='string'&&Boolean(value.locationId.trim())&&typeof value.currentKeyVersion==='number'&&Number.isSafeInteger(value.currentKeyVersion)&&value.currentKeyVersion>0);if(value.version!==1||value.publicKeyAlgorithm!==RETAIL_OFFLINE_SIGNATURE_ALGORITHM||typeof value.publicKey!=='string'||!value.publicKey||!value.privateKey||value.privateKey.type!=='private'||value.privateKey.extractable||value.privateKey.algorithm.name!=='Ed25519'||!value.privateKey.usages.includes('sign')||!validEnrollment)throw new TerminalIdentityError('Retail Offline Terminal identity is invalid.');try{const publicKey=await crypto.subtle.importKey('spki',Uint8Array.from(atob(value.publicKey),c=>c.charCodeAt(0)),{name:'Ed25519'},true,['verify']),challenge=new TextEncoder().encode('madina-retail-offline-terminal-keypair-consistency-v1'),signature=await crypto.subtle.sign({name:'Ed25519'},value.privateKey,challenge);if(!await crypto.subtle.verify({name:'Ed25519'},publicKey,signature,challenge))throw new Error()}catch{throw new TerminalIdentityError('Retail Offline Terminal identity is invalid.')}return{version:1,state:value.terminalId?'ENROLLED':'KEY_GENERATED',publicKeyAlgorithm:value.publicKeyAlgorithm,publicKey:value.publicKey,terminalId:value.terminalId,locationId:value.locationId,currentKeyVersion:value.currentKeyVersion,signOfflineEnvelope:envelope=>signRetailOfflineEnvelope(value.privateKey,envelope)}}
export async function loadTerminalIdentity():Promise<TerminalIdentity|undefined>{const db=await database();try{const value=await read(db);return value===undefined?undefined:await identity(value)}finally{db.close()}}
export async function generateTerminalIdentity():Promise<TerminalIdentity>{const db=await database();try{if(await read(db))throw new TerminalIdentityError('Retail Offline Terminal identity already exists.');const pair=await crypto.subtle.generateKey({name:'Ed25519'},false,['sign','verify']),value:StoredIdentity={version:1,publicKeyAlgorithm:RETAIL_OFFLINE_SIGNATURE_ALGORITHM,publicKey:await exportRetailOfflineTerminalPublicKey(pair.publicKey),privateKey:pair.privateKey};await write(db,value);return await identity(value)}finally{db.close()}}
export async function enrollTerminalIdentity(input:{terminalId:string;locationId:string;currentKeyVersion:number}):Promise<TerminalIdentity>{if(!input||typeof input.terminalId!=='string'||!input.terminalId.trim()||typeof input.locationId!=='string'||!input.locationId.trim()||!Number.isSafeInteger(input.currentKeyVersion)||input.currentKeyVersion<=0)throw new TerminalIdentityError('Retail Offline Terminal enrollment identity is invalid.');const db=await database();try{const value=await read(db);if(!value)throw new TerminalIdentityError('Retail Offline Terminal identity is missing.');if(value.terminalId!==undefined)throw new TerminalIdentityError('Retail Offline Terminal identity is already enrolled.');const enrolled:StoredIdentity={...value,terminalId:input.terminalId,locationId:input.locationId,currentKeyVersion:input.currentKeyVersion};await write(db,enrolled);return await identity(enrolled)}finally{db.close()}}
export async function clearTerminalIdentity():Promise<void>{const db=await database();try{await new Promise<void>((resolve,reject)=>{const transaction=db.transaction(storeName,'readwrite');transaction.objectStore(storeName).delete(recordKey);transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(new TerminalIdentityError('Retail Offline Terminal identity cannot be cleared.',{cause:transaction.error}))})}finally{db.close()}}
