import { createPublicKey, verify } from 'node:crypto'
import { expect, test } from '@playwright/test'
import { RETAIL_OFFLINE_SIGNATURE_PREFIX } from '@madina/retail'
import { verifyRetailOfflineEnvelope } from '../packages/database/src/retail/retailOfflineEnvelopeCrypto.ts'

const databaseName = 'madina-crm:retail-offline-terminal-identity:v1'
const envelope = { schemaVersion: 1, offlineOperationId: 'identity-browser-op', authorityId: 'authority-1', authorityVersion: 1, permitId: 'permit-1', permitSequence: 0, terminalId: 'terminal-1', terminalKeyVersion: 1, userId: 'user-1', locationId: 'location-1', proposedSaleId: 'sale-1', lines: [{ id: 'line-1', productId: 'product-1', quantity: 1, unitPriceMinor: 100 }], currencyCode: 'USD', currencyExponent: 2, cashAllocation: { id: 'payment-1', method: 'cash', amountMinor: 100, ordinal: 0 }, subtotalMinor: 100, payableTotalMinor: 100, claimedOfflineCompletedAt: '2026-09-22T00:00:00.000Z' } as const

test('production terminal identity persists a non-extractable key across reload and fails closed', async ({ page }) => {
  await page.goto('/')
  const initial = await page.evaluate(async () => { await new Promise<void>((resolve, reject) => { const request = indexedDB.deleteDatabase('madina-crm:retail-offline-terminal-identity:v1'); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error) }); const identity = await import('/src/shared/offline/terminalIdentity.ts'); return await identity.loadTerminalIdentity() })
  expect(initial).toBeUndefined()
  const generated = await page.evaluate(async () => { const identity = await import('/src/shared/offline/terminalIdentity.ts'); const value = await identity.generateTerminalIdentity(); const db = await new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open('madina-crm:retail-offline-terminal-identity:v1'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) }); const record = await new Promise<any>((resolve, reject) => { const request = db.transaction('identity', 'readonly').objectStore('identity').get('current'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) }); let exportFailed = false; try { await crypto.subtle.exportKey('pkcs8', record.privateKey) } catch { exportFailed = true }; db.close(); return { state: value.state, publicKey: value.publicKey, privateExtractable: record.privateKey.extractable, exportFailed } })
  expect(generated).toMatchObject({ state: 'KEY_GENERATED', privateExtractable: false, exportFailed: true })
  await page.reload()
  const afterReload = await page.evaluate(async input => { const identity = await import('/src/shared/offline/terminalIdentity.ts'); const value = await identity.loadTerminalIdentity(); if (!value) throw new Error('identity missing'); const signed = await value.signOfflineEnvelope(input); const db = await new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open('madina-crm:retail-offline-terminal-identity:v1'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) }); const record = await new Promise<any>((resolve, reject) => { const request = db.transaction('identity', 'readonly').objectStore('identity').get('current'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) }); let exportFailed = false; try { await crypto.subtle.exportKey('pkcs8', record.privateKey) } catch { exportFailed = true }; db.close(); return { publicKey: value.publicKey, signature: signed.signature, payloadHash: signed.payloadHash, privateExtractable: record.privateKey.extractable, exportFailed } }, envelope)
  expect(afterReload.publicKey).toBe(generated.publicKey); expect(afterReload.privateExtractable).toBe(false); expect(afterReload.exportFailed).toBe(true); expect(Buffer.from(afterReload.signature.slice(RETAIL_OFFLINE_SIGNATURE_PREFIX.length), 'base64')).toHaveLength(64)
  expect(verifyRetailOfflineEnvelope({ envelope, payloadHash: afterReload.payloadHash, signature: afterReload.signature, keyAlgorithm: 'ed25519-spki-der-base64-v1', publicKey: afterReload.publicKey }).payloadHash).toBe(afterReload.payloadHash)
  expect(verify(null, Buffer.from('unused'), createPublicKey({ key: Buffer.from(afterReload.publicKey, 'base64'), format: 'der', type: 'spki' }), Buffer.alloc(64))).toBe(false)
const failures = await page.evaluate(async () => { const db = await new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open('madina-crm:retail-offline-terminal-identity:v1'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) }); const get = () => new Promise<any>((resolve, reject) => { const request = db.transaction('identity', 'readonly').objectStore('identity').get('current'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) }); const put = (value:any) => new Promise<void>((resolve, reject) => { const transaction = db.transaction('identity', 'readwrite'); transaction.objectStore('identity').put(value, 'current'); transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error) }); const original = await get(); await put({ ...original, privateKey: undefined }); const identity = await import('/src/shared/offline/terminalIdentity.ts'); const missingKey = await identity.loadTerminalIdentity().then(() => false, () => true); await put({ ...original, terminalId: 'terminal-1' }); const partialEnrollment = await identity.loadTerminalIdentity().then(() => false, () => true); const other=await crypto.subtle.generateKey({name:'Ed25519'},false,['sign','verify']),spki=await crypto.subtle.exportKey('spki',other.publicKey),base64=btoa(String.fromCharCode(...new Uint8Array(spki))); await put({...original,publicKey:base64}); const swapped=await identity.loadTerminalIdentity().then(() => false, () => true); await put(original); db.close(); await identity.clearTerminalIdentity(); const cleared = await identity.loadTerminalIdentity(); const replacement = await identity.generateTerminalIdentity(); return { missingKey, partialEnrollment, swapped, cleared: cleared === undefined, replacementState: replacement.state, replacementTerminal: replacement.terminalId } })
  expect(failures).toEqual({ missingKey: true, partialEnrollment: true, swapped: true, cleared: true, replacementState: 'KEY_GENERATED', replacementTerminal: undefined })
})
