import { useEffect, useRef, useState } from 'react'
import type { RetailLocation } from '@madina/retail'
import { Alert, Button, Card, EmptyState, Input, Select, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@madina/ui'
import { getRetailInventory, getRetailLocations, getRetailMovementHistory, type RetailInventoryPage, type RetailMovementPage } from '../../shared/api/retailApi'
import { retailMovementSourceLabel, retailMovementTypeLabel } from '../../shared/retail/presentation'

export function RetailInventory() {
  const [locations,setLocations]=useState<RetailLocation[]>([]),[locationId,setLocationId]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState<RetailInventoryPage>(),[error,setError]=useState<string>(),[loading,setLoading]=useState(true),[history,setHistory]=useState<RetailMovementPage>(),[historyTitle,setHistoryTitle]=useState('')
  const generation=useRef(0)
  function load(nextLocationId=locationId,cursor?:string,append=false){if(!nextLocationId)return;const request=++generation.current;setLoading(true);setError(undefined);void getRetailInventory(nextLocationId,{search:search||undefined,cursor}).then(value=>{if(request!==generation.current)return;setPage(previous=>append&&previous?{items:[...previous.items,...value.items],nextCursor:value.nextCursor}:value)}).catch(reason=>request===generation.current&&setError(reason instanceof Error?reason.message:'Не удалось загрузить остатки.')).finally(()=>request===generation.current&&setLoading(false))}
  useEffect(()=>{void getRetailLocations().then(value=>{setLocations(value);if(value[0]){setLocationId(value[0].id);load(value[0].id)}else setLoading(false)}).catch(reason=>{setError(reason instanceof Error?reason.message:'Не удалось загрузить точки.');setLoading(false)})},[])
  function openHistory(productId:string,name:string){if(!locationId)return;setHistoryTitle(name);setHistory(undefined);void getRetailMovementHistory(locationId,productId).then(setHistory).catch(reason=>setError(reason instanceof Error?reason.message:'Не удалось загрузить движения.'))}
  return <section><header><h1>Розница: остатки</h1><p>Авторитетные остатки retail по выбранной разрешённой точке.</p></header><Card><label>Точка <Select value={locationId} onChange={event=>{setLocationId(event.target.value);load(event.target.value)}}><option value="">Выберите точку</option>{locations.map(location=><option key={location.id} value={location.id}>{location.name} ({location.code})</option>)}</Select></label><label>Поиск товара или штрихкода <Input value={search} onChange={event=>setSearch(event.target.value)} /></label><Button type="button" onClick={()=>load()}>Найти</Button></Card>{error&&<Alert variant="danger" title="Не удалось выполнить операцию">{error}</Alert>}{loading?<p>Загрузка остатков…</p>:page?.items.length?<Card><Table><TableHead><TableRow><TableHeader>Товар</TableHeader><TableHeader>Штрихкод</TableHeader><TableHeader>Остаток</TableHeader><TableHeader>Обновлено</TableHeader><TableHeader>История</TableHeader></TableRow></TableHead><TableBody>{page.items.map(item=><TableRow key={item.productId}><TableCell>{item.name} ({item.sourceId})</TableCell><TableCell>{item.barcodes.join(', ')||'—'}</TableCell><TableCell>{item.onHandQuantity}</TableCell><TableCell>{item.updatedAt?new Date(item.updatedAt).toLocaleString('ru-RU'):'—'}</TableCell><TableCell><Button type="button" variant="secondary" onClick={()=>openHistory(item.productId,item.name)}>Движения</Button></TableCell></TableRow>)}</TableBody></Table>{page.nextCursor&&<Button type="button" variant="secondary" onClick={()=>load(locationId,page.nextCursor,true)}>Показать ещё</Button>}</Card>:<EmptyState title="Товары не найдены" description="Активных retail-товаров для выбранного поиска нет." />}{history&&<Card><h2>Движения: {historyTitle}</h2><p>Текущий остаток: {history.balance?.onHandQuantity??0}</p><Table><TableHead><TableRow><TableHeader>Время</TableHeader><TableHeader>Тип</TableHeader><TableHeader>Изменение</TableHeader><TableHeader>Источник</TableHeader></TableRow></TableHead><TableBody>{history.movements.map(movement=><TableRow key={movement.id}><TableCell>{new Date(movement.createdAt).toLocaleString('ru-RU')}</TableCell><TableCell>{retailMovementTypeLabel(movement.type)}</TableCell><TableCell>{movement.quantityDelta>0?`+${movement.quantityDelta}`:movement.quantityDelta}</TableCell><TableCell>{retailMovementSourceLabel(movement.sourceType, movement.sourceLabel)}</TableCell></TableRow>)}</TableBody></Table></Card>}</section>
}
